/**
 * A small gettext PO reader, shared by the i18n scripts.
 *
 * Deliberately hand-rolled rather than a dependency. These scripts live at the repo root, which has
 * no package.json of its own, and the only structure any of them needs is "blocks separated by blank
 * lines, each with a msgid, a msgstr, some comments and maybe a fuzzy flag".
 *
 * The two flags that matter downstream:
 *   - `fuzzy` means "needs review". A machine translation carries it; a human clearing it is the
 *     signal that somebody has actually looked. Everything in this pipeline keys off that one bit
 *     rather than a side-channel state file, so a plain `git pull` of a translator's commits cannot
 *     put the two out of step.
 *   - `obsolete` (`#~`) is the extractor's own bookkeeping: an entry whose source text was reworded,
 *     kept so its translation is not simply lost. Not part of the live catalogue.
 */

import { readFileSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
export const LOCALES = join(ROOT, 'locales')
export const SOURCE_LOCALE = 'en'
export const COMPONENTS = ['client', 'server']

export function unescapePo(s) {
  return s
    .replace(/\\n/g, '\n')
    .replace(/\\t/g, '\t')
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\')
}

/** Every locale directory, source first. */
export function locales() {
  const all = readdirSync(LOCALES, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
  return [SOURCE_LOCALE, ...all.filter((l) => l !== SOURCE_LOCALE)]
}

export function catalogPath(locale, component) {
  return join(LOCALES, locale, `${component}.po`)
}

/**
 * Reads one catalogue into a Map of key to entry.
 *
 * An entry is `{ key, value, fuzzy, comments, references, sourceText }`, where `value` is the
 * translation (empty when untranslated) and `sourceText` is the English pulled out of the
 * `#. English: ...` comment the sync script writes, when there is one.
 */
export function readCatalog(locale, component) {
  const path = catalogPath(locale, component)
  const entries = new Map()
  if (!existsSync(path)) return entries

  const text = readFileSync(path, 'utf8')
  const blocks = text.split(/\n\s*\n/)

  for (const block of blocks) {
    if (!block.trim()) continue
    // Obsolete entries are not live.
    if (/^#~/m.test(block)) continue

    const lines = block.split('\n')
    const key = joined(lines, 'msgid')
    if (key === null || key === '') continue // null means absent; empty is the header

    const comments = lines.filter((l) => l.startsWith('#.')).map((l) => l.slice(2).trim())
    const english = comments.find((c) => c.startsWith('English: '))

    entries.set(key, {
      key,
      value: joined(lines, 'msgstr') ?? '',
      fuzzy: lines.some((l) => /^#,.*\bfuzzy\b/.test(l)),
      comments,
      references: lines.filter((l) => l.startsWith('#:')).map((l) => l.slice(2).trim()),
      sourceText: english ? english.slice('English: '.length) : null,
    })
  }
  return entries
}

/** A PO value, joined across the folded continuation lines that follow it. */
function joined(lines, field) {
  const start = lines.findIndex((l) => l.startsWith(`${field} `))
  if (start === -1) return null

  const first = lines[start].slice(field.length + 1).trim()
  let out = first.startsWith('"') ? unescapePo(first.slice(1, -1)) : ''

  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i].trim()
    if (!line.startsWith('"')) break
    out += unescapePo(line.slice(1, -1))
  }
  return out
}

/**
 * What a translator has to produce for this key: the English text.
 *
 * The two catalogues answer this differently, on purpose. Client keys are generated by
 * `lingui extract` and ARE the English, because nothing outside the frontend refers to them. Server
 * keys are explicit dotted names a `.cs` file has to be able to write, so the English lives in the
 * source catalogue's own translation and is mirrored into a comment for the others.
 */
export function sourceTextFor(key, entry, sourceCatalog, component) {
  if (component === 'client') return key
  const fromSource = sourceCatalog.get(key)
  return fromSource?.value || entry?.sourceText || key
}
