// <auto-generated />
using System;
using Maki.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maki.Data.Migrations
{
    [DbContext(typeof(MakiDbContext))]
    partial class MakiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Maki.Core.Entities.AppConfigEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppConfig");
                });

            modelBuilder.Entity("Maki.Core.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterFileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOneShot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Number")
                        .HasColumnType("REAL");

                    b.Property<string>("NumberRaw")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterFileId");

                    b.HasIndex("SeriesId", "Number", "Volume", "Language");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Maki.Core.Entities.ChapterFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("ChapterFiles");
                });

            modelBuilder.Entity("Maki.Core.Entities.DownloadQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttempt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseInfoJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SourceMappingId");

                    b.HasIndex("Status");

                    b.ToTable("DownloadQueue");
                });

            modelBuilder.Entity("Maki.Core.Entities.NamingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterFileFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterFileFormatWithVolume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RenameChapters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesFolderFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NamingConfigs");
                });

            modelBuilder.Entity("Maki.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnChapterDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnDownloadFailed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnHealthIssue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnImportCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnNewChapterAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Maki.Core.Entities.ReadingState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KavitaSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastProgressAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxChapter")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxVolume")
                        .HasColumnType("REAL");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KavitaSeriesId")
                        .IsUnique();

                    b.HasIndex("SeriesId");

                    b.ToTable("ReadingStates");
                });

            modelBuilder.Entity("Maki.Core.Entities.RootFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RootFolders");
                });

            modelBuilder.Entity("Maki.Core.Entities.ScrobbleLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScrobbleLog");
                });

            modelBuilder.Entity("Maki.Core.Entities.ScrobbleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KavitaSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KavitaSeriesId", "Service")
                        .IsUnique();

                    b.ToTable("ScrobbleMappings");
                });

            modelBuilder.Entity("Maki.Core.Entities.ScrobbleSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("KavitaSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyncedAt");

                    b.HasIndex("KavitaSeriesId", "Service")
                        .IsUnique();

                    b.ToTable("ScrobbleSyncStates");
                });

            modelBuilder.Entity("Maki.Core.Entities.ScrobbleToken", b =>
                {
                    b.Property<string>("Service")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Service");

                    b.ToTable("ScrobbleTokens");
                });

            modelBuilder.Entity("Maki.Core.Entities.ScrobbleUnmatched", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KavitaSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KavitaSeriesId", "Service")
                        .IsUnique();

                    b.ToTable("ScrobbleUnmatched");
                });

            modelBuilder.Entity("Maki.Core.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Added")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AniListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorArt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorStory")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMetadataRefresh")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaBakaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MangaDexUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("MangaUpdatesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonitorNewItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumberingClash")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RootFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalVolumes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MangaBakaId");

                    b.HasIndex("RootFolderId");

                    b.HasIndex("SortTitle");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Maki.Core.Entities.SourceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRefresh")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSeriesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "SourceName")
                        .IsUnique();

                    b.ToTable("SourceMappings");
                });

            modelBuilder.Entity("Maki.Core.Entities.StatsEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KavitaSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Type", "Timestamp");

                    b.ToTable("StatsEvents");
                });

            modelBuilder.Entity("Maki.Core.Entities.Chapter", b =>
                {
                    b.HasOne("Maki.Core.Entities.ChapterFile", "ChapterFile")
                        .WithMany()
                        .HasForeignKey("ChapterFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Maki.Core.Entities.Series", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterFile");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Maki.Core.Entities.ChapterFile", b =>
                {
                    b.HasOne("Maki.Core.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maki.Core.Entities.DownloadQueueItem", b =>
                {
                    b.HasOne("Maki.Core.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maki.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maki.Core.Entities.SourceMapping", "SourceMapping")
                        .WithMany()
                        .HasForeignKey("SourceMappingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Series");

                    b.Navigation("SourceMapping");
                });

            modelBuilder.Entity("Maki.Core.Entities.ReadingState", b =>
                {
                    b.HasOne("Maki.Core.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Maki.Core.Entities.Series", b =>
                {
                    b.HasOne("Maki.Core.Entities.RootFolder", "RootFolder")
                        .WithMany()
                        .HasForeignKey("RootFolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RootFolder");
                });

            modelBuilder.Entity("Maki.Core.Entities.SourceMapping", b =>
                {
                    b.HasOne("Maki.Core.Entities.Series", "Series")
                        .WithMany("SourceMappings")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Maki.Core.Entities.StatsEvent", b =>
                {
                    b.HasOne("Maki.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Maki.Core.Entities.Series", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("SourceMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
